# Generated by Django 4.2.16 on 2024-11-19 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Trail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("location", models.CharField(max_length=200)),
                (
                    "difficulty",
                    models.CharField(
                        choices=[
                            ("Easy", "Easy"),
                            ("Moderate", "Moderate"),
                            ("Hard", "Hard"),
                        ],
                        max_length=50,
                    ),
                ),
                ("distance", models.FloatField()),
                ("elevation_gain", models.FloatField()),
                ("rating", models.FloatField()),
            ],
        ),
    ]
