# Generated by Django 4.2.16 on 2024-11-19 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trails", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="trail", old_name="elevation_gain", new_name="elevation",
        ),
        migrations.AlterField(
            model_name="trail",
            name="difficulty",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="trail", name="location", field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="trail", name="name", field=models.CharField(max_length=255),
        ),
    ]
